import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import ErrorWrapper from "./error-wrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "Next.js Learning",
    template: "%s | Next.js"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative flex flex-col justify-between min-h-screen`} 
      >
        <section>
        <header style={{
          backgroundColor: 'lightblue',
          padding: "1rem"
        }}>
          <p>Header</p>
          
        </header>
          <NavBar />
        <ErrorWrapper>
        {children}
        </ErrorWrapper>
        </section>
        <footer style={{
          backgroundColor: 'ghostwhite',
          padding: "1rem",
          textAlign: "center"
        }}>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
